CREATE TABLE PRODUTOS (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR,
	DESCRICAO VARCHAR,
	PRECO DECIMAL, 
	QUANTIDADE INTEGER
);

INSERT
	INTO
	PRODUTOS (NOME,
	DESCRICAO,
	PRECO,
	QUANTIDADE)
VALUES 
('Camisa','Preta',19.9,10),('Camisa','Vermelha',19.9,5),('Fone JBL','BT 5.2',599.9,2);